# Generated by Django 5.2.9 on 2025-12-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='figma_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
