# Generated by Django 5.2.9 on 2025-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_figma_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectGallery',
            new_name='Gallery',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projects.tag'),
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
    ]
